### PR TITLE
Update dependencies to the latest versions

### PR DESCRIPTION
**Pull request by TimvdLippe**
I ran this package on Node 10 and gotten a lot of V8 internal errors. Updating the dependencies resolved this issue.

### CODE REVIEW

**Comment by TimvdLippe** [comment]
The ShadyDOM update broke some tests. Extracted an issue for that instead: https://github.com/webcomponents/shadycss/issues/212

**Comment by azakus** [comment]
Yep, I'll merge this and address #212

**Comment by azakus** [comment]
Hmm, tests are _passing_ now. I'll verify that #212 is still valid.

**Comment by azakus** [comment]
Oh I see, your package.json went back to 1.1.2

**Pull request merged**
