### PR TITLE
Support semicolons in quotes and parenthesis in custom property values

### PR DESCRIPTION
**Pull request by tomalec**
Fixes
 - Polymer/polymer/issues/4288
 - webcomponents/shadycss/issues/47

RegExp for CSS value should consider parenthesis or quotes that could contain `;`

### CODE REVIEW

**Comment by tomalec** [comment]
//cc @azakus @sorvell is there any chance to get this merged, or get some feedback?

**Comment by azakus** [comment]
Sorry for the delay, we've been super busy trying to get Polymer 2.0 RC out the door. Could you rebase and add a test case?

**Comment by tomalec** [comment]
Thanks for feedback :)

I have pushed tests to Polymer 1.x PRs, for this one it may take me some time, as  I cannot find any existing tests for `collectProperties` (https://github.com/webcomponents/shadycss/blob/master/src/style-properties.js#L80) and this issue seems to be related to Polymer http://jsbin.com/woyawo/edit?html,output

I will try to do it over the weekend.

**Comment by tomalec** [comment]
@azakus I have just added test case and travis-ci seems happy

**Comment by tomalec** [comment]
I have also rebased it and removed dist files for better readability.

**Comment by tomalec** [comment]
@azakus Could you please take a look?

**Comment by tomalec** [comment]
@azakus, @sorvell ping, is there any chance to get it in 1.0.0? In Polymer 1.x I was able to workaround it by overwriting `Polymer.StyleUtil.rx.VAR_ASSIGN` now it's not so easy, what makes it a show stopper (migration stopper) for us and all our users.

**Comment by azakus** [comment]
Whoops, sorry this fell of the radar. Let me just try the polymer tests with this patch.

**Comment by azakus** [comment]
LGTM!

**Comment by tomalec** [comment]
Great! thanks :)

**Pull request merged**
